"""Tests for auto-generated UI tabs for plugins without ui_config."""

import pytest
from httpx import ASGITransport, AsyncClient
from fastapi import FastAPI

from adwatch.models import RawAdvertisement, Classification
from adwatch.registry import ParserRegistry
from adwatch.storage.base import Database
from adwatch.storage.migrations import run_migrations
from adwatch.storage.raw import RawStorage
from adwatch.dashboard.routers.overview import create_overview_router


class FakeParserNoUI:
    """A parser with no ui_config method."""
    def parse(self, raw):
        return None


class FakeParserWithUI:
    """A parser that provides its own ui_config."""
    def parse(self, raw):
        return None

    def ui_config(self):
        from adwatch.models import PluginUIConfig, WidgetConfig
        return PluginUIConfig(
            tab_name="Custom",
            widgets=[WidgetConfig(widget_type="data_table", title="Custom Table", data_endpoint="/api/custom/data")],
        )


@pytest.fixture
async def db(tmp_path):
    database = Database()
    await database.connect(str(tmp_path / "test.db"))
    await run_migrations(database)
    yield database
    await database.close()


@pytest.fixture
async def raw_storage(db):
    return RawStorage(db)


@pytest.fixture
def registry_mixed():
    """Registry with both ui_config and non-ui_config plugins."""
    reg = ParserRegistry()
    reg.register(
        name="govee", company_id=0xEC88,
        description="Govee Sensors", version="1.0.0", core=False,
        instance=FakeParserNoUI(),
    )
    reg.register(
        name="custom_plugin", company_id=0x1234,
        description="Custom Plugin", version="1.0.0", core=False,
        instance=FakeParserWithUI(),
    )
    return reg


class TestAutoGeneratedUI:
    """Plugins without ui_config should get auto-generated tabs."""

    @pytest.fixture
    async def client(self, registry_mixed, db, raw_storage):
        router = create_overview_router(raw_storage, registry_mixed)
        app = FastAPI()
        app.include_router(router)
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as c:
            yield c

    @pytest.mark.asyncio
    async def test_plugins_ui_includes_all_plugins(self, client):
        resp = await client.get("/api/plugins/ui?all=true")
        assert resp.status_code == 200
        data = resp.json()
        tab_names = [c["tab_name"] for c in data]
        assert "Govee" in tab_names
        assert "Custom" in tab_names

    @pytest.mark.asyncio
    async def test_auto_generated_tab_has_data_table(self, client):
        resp = await client.get("/api/plugins/ui?all=true")
        data = resp.json()
        govee_cfg = [c for c in data if c["tab_name"] == "Govee"][0]
        assert len(govee_cfg["widgets"]) >= 1
        widget = govee_cfg["widgets"][0]
        assert widget["widget_type"] == "data_table"
        assert "recent" in widget["data_endpoint"].lower()

    @pytest.mark.asyncio
    async def test_custom_ui_not_overridden(self, client):
        resp = await client.get("/api/plugins/ui?all=true")
        data = resp.json()
        custom_cfg = [c for c in data if c["tab_name"] == "Custom"][0]
        assert custom_cfg["widgets"][0]["data_endpoint"] == "/api/custom/data"


class TestGenericRecentEndpoint:
    """Generic /api/parser/{name}/recent endpoint for any registered parser."""

    @pytest.fixture
    def registry_single(self):
        reg = ParserRegistry()
        reg.register(
            name="govee", company_id=0xEC88,
            description="Govee Sensors", version="1.0.0", core=False,
            instance=FakeParserNoUI(),
        )
        return reg

    @pytest.fixture
    async def app_client(self, registry_single, db, raw_storage):
        from adwatch.dashboard.app import create_app
        from adwatch.dashboard.websocket import WebSocketManager
        ws = WebSocketManager()
        app = create_app(raw_storage, None, registry_single, ws, db=db)
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as c:
            yield c

    @pytest.mark.asyncio
    async def test_generic_recent_returns_data(self, app_client, raw_storage):
        ad = RawAdvertisement(
            timestamp="2025-01-15T10:30:00+00:00",
            mac_address="GO:VE:E0:00:00:01",
            address_type="random",
            manufacturer_data=None,
            service_data=None,
        )
        await raw_storage.save(
            ad,
            Classification(ad_type="govee", ad_category="sensor", source="company_id"),
            parsed_by=["govee"],
        )
        resp = await app_client.get("/api/parser/govee/recent")
        assert resp.status_code == 200
        data = resp.json()
        assert len(data) == 1
        assert data[0]["mac_address"] == "GO:VE:E0:00:00:01"

    @pytest.mark.asyncio
    async def test_generic_recent_404_unknown_parser(self, app_client):
        resp = await app_client.get("/api/parser/nonexistent/recent")
        assert resp.status_code == 404

    @pytest.mark.asyncio
    async def test_generic_recent_empty(self, app_client):
        resp = await app_client.get("/api/parser/govee/recent")
        assert resp.status_code == 200
        assert resp.json() == []
